config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :t_unidades
  get '/organigrama/:id', to: 't_unidades#organigrama', as: 'organigrama'
  get '/organigrama', to: 't_unidades#organigrama'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/tree.rb
# encoding: UTF-8
module Tree
    extend ActiveSupport::Concern
  
    included do
      has_ancestry # :orphan_strategy => :adopt
  #    def name_for_selects
  #     "#{'|' if depth > 0}" + "#{'---' * depth} #{id}"
  #    end
  
  #    def name_for_tree
  #      "<span class='tree_#{depth}'>#{id}</span>".html_safe
  #    end
  
      def possible_parents
        parents = self.class.arrange_as_array#(:order => 'name')
        return new_record? ? parents : parents - subtree
      end
    end
  
    module ClassMethods
      def arrange_as_array(options={}, hash=nil)
        hash ||= arrange(options) unless hash.is_a? Array
  
        arr = []
  
        hash.each do |node, children|
          arr << node
          arr += arrange_as_array(options, children) unless children.nil?
        end
        arr
      end
    end
  
  end

app/models/t_unidad.rb
class TUnidad < ApplicationRecord
    include Tree
    
	self.table_name ="geslico.dbo.TUnidades"		

    has_one :t_unidad, :foreign_key => "nCodUniPadre"

    belongs_to :t_unidad, :foreign_key => "nIdArea", :primary_key => "nCodUni"
    belongs_to :t_unidad, :foreign_key => "nCodUniPadre", :primary_key => "nCodUni"
    
    has_ancestry
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/t_unidades_controller.rb
class TUnidadesController < ApplicationController

    before_action :set_t_unidad, only: [:show, :edit, :update, :destroy]
    
    # GET /organigrama
    
      # def organigrama
          # params[:id]=10000000 if !params[:id]  
          # @organigrama = TUnidad.find(params[:id])            
      # end

      # GET /t_unidades
      def index                
        @t_unidad = TUnidad.all
        @organigrama = TUnidad.select(:nCodUni, :nCodUniPadre, :cDenominacion, :nIdArea, :ancestry, :norder).all.arrange({:order => 'norder'}) 
      end

      def show
      end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_t_unidad
        @t_unidad = TUnidad.find(params[:id])                    
      end
  
      # Never trust parameters from the scary internet, only allow the white list through.
      def t_unidad_params        
        params.require(:t_unidad).permit(:nCodUni, :nCodUniPadre, :nIdArea, :cDenominacion, :norder)
      end      
end

app/helpers/ancestry_helper.rb
# app/helpers/ancestry_helper.rb
module AncestryHelper
    # arranged as tree expects 3 arguments. The hash from has_ancestry.arrange() method, 
    # options, and a render block
    def arranged_tree_as_list(hash, options = {}, &block)
  
      options = {
        :list_type            => :ul,
        :list_style           => '', 
        :ul_class             => [],
        :ul_class_top         => [],
        :ul_class_children    => [],
        :li_class             => [],
        :li_class_top         => [],
        :li_class_children    => [],
        :sort_by              => []
      }.merge(options)
  
      # setup any custom list styles you want to use here. An example is excluded
      # to render bootstrap style list groups. This is used to keep from recoding the same
      # options on different lists      
      case options[:list_style]
        #Creo nuestros propios class para foundation
        when :accordion_list_group           
          options[:ul_class_top] << ['vertical menu accordion-menu is-active']
          options[:ul_class_children] << ['menu vertical nested']          
      end
      options[:list_style] = ''
  
      output = ''
  
      # sort the hash key based on sort_by options array
      unless options[:sort_by].empty?
        hash = Hash[hash.sort_by{|k, v| options[:sort_by].collect {|sort| k.send(sort)} } ]
      end
  
      current_depth = 0
      # and here... we... go...
      hash.each do |object, children|
          
          li_classes = options[:li_class]  
                
          if object.depth == 0
            li_classes += options[:li_class_top]
          else
            li_classes += options[:li_class_children]
          end 
                 
          if children.size > 0
            output << content_tag(:li, capture(object, &block) + arranged_tree_as_list(children, options, &block).html_safe)
          else
            output << content_tag(:li, capture(object, &block)).html_safe
            current_depth = object.depth
          end
  
      end
  
      unless output.blank?
        
        ul_classes = options[:ul_class]
        
        if current_depth == 0
          ul_classes += options[:ul_class_top]
          output = content_tag(options[:list_type], output.html_safe,  'data-submenu-toggle' => true, 'data-accordion-menu' => '')
        else
          ul_classes += options[:ul_class_children] 
          output = content_tag(options[:list_type], output.html_safe)
        end      
 
      end
      
      return output.html_safe
       
    end
  
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

  </body>
</html>

app/views/t_unidades/_children.html.erb
<% i=item.depth %>

<% item.children.each do |a| %>    
    <% while i>a.depth %>
        <% i=i-1 %>
        </ul>
    <% end %>
    <% if i<a.depth %>
        <ul class="menu vertical nested submenu is-accordion-submenu" data-submenu >                
        <% i=i+1 %>
    <% end %>

    <li role="treeitem" class="is-accordion-submenu-parent has-submenu-toggle">            
        <%= link_to "#{a.nCodUni} - #{a.cDenominacion}" , organigrama_url(a)  %>         
        
    </li>
    <% if a.nCodUni==10000001 %>             
        <%= render partial: "children", object: a, as: :item %>        
        </ul>
    <% end %>
<% end %>        

app/views/t_unidades/index.html.erb
<div class="row">
  
    <%= arranged_tree_as_list(@organigrama, {:list_style => :accordion_list_group}) do |nodo| %>    
      <%= link_to "#{nodo.nCodUni} - #{nodo.cDenominacion}" %>
    <% end %>
  
</div> 

app/views/t_unidades/organigrama.html.erb
<h1>Organigrama Municipal</h1>
<h2>organigrama.html.erb</h2>

<div class="tree">

    <ul class="vertical menu accordion-menu" data-accordion-menu data-submenu-toggle="true" role="tree" aria-multiselectable="true">                            
        <li role="treeitem" class="is-accordion-submenu-parent has-submenu-toggle">                
            <%= link_to "#{@organigrama.nCodUni} - #{@organigrama.cDenominacion}", (organigrama_url(@organigrama.parent) if @organigrama.parent) %>              
        </li>    
        <%= render partial: "children", object: @organigrama, as: :item %>
    </ul>
</div>